blob:
  storage:
    endpoint: https://sistemasdistribuidos.blob.core.windows.net/
    connection: sp=racwdli&st=2023-06-07T02:22:41Z&se=2023-06-07T10:22:41Z&spr=https&sv=2022-11-02&sr=c&sig=ELcNeL5eCjf9LZeKpWitXVC7wok%2BH07KOTpKJRsCLOw%3D
  container:
    directory: diretorioblob