blob:
  storage:
    endpoint: https://sistemasdistribuidos.blob.core.windows.net/
    connection: sp=r&st=2023-06-07T02:17:31Z&se=2023-06-07T10:17:31Z&spr=https&sv=2022-11-02&sr=c&sig=NaZyUxGQMMjIUbGuzn%2FaYli4HYB2WHJ6cEnP4MEfCSY%3D
  container:
    directory: diretorioblob